### ISSUE TITLE
Official ZIP file doesn't preserve permissions

### ISSUE THREAD

**Issue by mistydemeo** [harvard-lts/fits#11]
The official FITS 0.8.0 release is provided only as a ZIP file, which doesn't preserve permissions. On Unix systems, this means that the scripts can't be directly executed without a `chmod +x`. It would be great to distribute a tarball for Unix systems alongside the ZIP for Windows.

**Comment by pwinckles** [comment]
@daveneiman Assuming you just upload the zip that's produced by the maven build, this is no longer an issue.

**Comment by daveneiman** [comment]
Yes, the Maven-generate zip file is now what's uploaded to GitHub.
