### ISSUE TITLE
Frequent startup failures on slower linux machines

### ISSUE THREAD

**Issue by phebal** [harvard-lts/fits#120]
The versions I've tested that are affected are 1.0.1 and 1.0.3.  I've ran into it on CentOS and Fedora. It happens only occasionally on faster machines and very frequently on slower ones. This bug report's logs were generated on a slow vm running CentOS 7.2.1511, kernel 3.10.0-327.18.2.el7.x86_64

The error looks like it's caused by a missing native MediaInfo library:

```
Exception in thread "main" edu.harvard.hul.ois.fits.exceptions.FitsToolException: Error loading native library for MediaInfo please check that fits_home is properly set
```

However, the library is there and sometimes the program starts up just fine. This error is completely eliminated by running: `export LD_LIBRARY_PATH=/var/www/apps/fits-1.0.3/tools/mediainfo/linux` prior to running `fits.sh`.

Here's a strace logs showing failure: https://northwestern.box.com/s/t3os4b3106ba4eh28rq0yv3jjlhxv4e9 and success: https://northwestern.box.com/s/k9nksrmympypw7ywcncvbv22858yf9zc on the same machine. I've collected them by running:
`strace -F -f /var/www/apps/fits-1.0.3/fits.sh -i /var/www/apps/shib/nu-idp-metadata.xml`

In the log showing failure, it looks like it finds both libraries just fine at one point during the execution:

```
[pid 31514] open("/var/www/apps/fits-1.0.3/tools/mediainfo/linux/libzen.so.0", O_RDONLY|O_CLOEXEC) = 40
[pid 31514] open("/var/www/apps/fits-1.0.3/tools/mediainfo/linux/libzen.so.0", O_RDONLY|O_CLOEXEC) = 40
```

However it then fails right after making these two calls:

```
[pid 31514] stat("/var/www/apps/fits-1.0.3/linux-x86-64/libmediainfo.so", 0x7fe80d73c440) = -1 ENOENT (No such file or directory)
[pid 31514] stat("/var/www/apps/fits-1.0.3/libmediainfo.so", 0x7fe80d73c440) = -1 ENOENT (No such file or directory) 
```

I'm not a Java programmer but might take a stab at trying to debug this further if I find some time.

**Comment by dbirtwell** [comment]
phebal:

Please view the FAQ for FITS at : http://projects.iq.harvard.edu/fits/fitsfaq.

This FAQ states the following:

Currently, video support in FITS via MediaInfo will ONLY support 64­-bit OSes with a 64­-bit Java Virtual Machines (JVM).

The FITS MediaInfo tool will detect whether the OS is Windows/Mac OS X/LINUX and dynamically load the associated MediaInfo libraries for any of these OSes.

Out of the box, the FITS MediaInfo tool will ONLY be supporting the following 64-bit OSes: 

Windows 7, or higher - 64-bit (only tested with Windows 7)
Mac OS - 64-bit
Red Hat 6 x86_64 - 64-bit 
 ...

There are some details there about how to install the libraries for other 64-bit OSes, but you can turn off the MediaInfo tool if you don't need video support.

This can be done by commenting out the following line in the FITS xml configuration file which lives in <fits_installation_folder>/xml/fits.xml

        <tool class="edu.harvard.hul.ois.fits.tools.mediainfo.MediaInfo" include-exts="avi,mov,mpg,mpeg,mkv,mp4,mxf,ogv,mj2,divx,dv,m4v,m2v,ismv,m2ts,mpeg4" classpath-dirs="lib/mediainfo" />

Thanks for your interest in using FITS.

Dave B.

**Comment by phebal** [comment]
Thanks for responding Dave,

The problem is that I have the right libraries in place. The program only fails once in a while, not all the time. I can make it run fine every time if I export the `LD_LIBRARY_PATH` env variable and point it at the `tools/mediainfo/linux` folder in FITS home. From the FAQ, this folder should be detected automatically, as long as the right libraries are there, and they are:
```
ldd /var/www/apps/fits-1.0.3/tools/mediainfo/linux/lib*
/var/www/apps/fits-1.0.3/tools/mediainfo/linux/libmediainfo.so.0:
	linux-vdso.so.1 =>  (0x00007ffd673d2000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fecdfe58000)
	libzen.so.0 => not found
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fecdfc3b000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fecdf933000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fecdf631000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fecdf26e000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fecdf058000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fece07dd000)
/var/www/apps/fits-1.0.3/tools/mediainfo/linux/libzen.so.0:
	linux-vdso.so.1 =>  (0x00007fff6c0aa000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fad5bcaf000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fad5b9a7000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fad5b6a4000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fad5b2e2000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fad5b0cc000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fad5c11b000)
```

**Comment by dbirtwell** [comment]
phebal:

Thanks for responding and giving me more details. In all of the other reported failures on LINUX machines it was due to attempting to run on an unsupported OS and/or JVM architecture.

One thing I find interesting in your installation is that you are using OpenJDK. As far as I know, FITS with MediaInfo support hasn't been tested with OpenJDK.

We'll look into this and get back to you as soon as we can.

Thanks,

Dave B.

**Comment by dbirtwell** [comment]
phebal:

I just saw the following:

*However, the library is there and sometimes the program starts up just fine. This error is completely eliminated by running: export LD_LIBRARY_PATH=/var/www/apps/fits-1.0.3/tools/mediainfo/linux prior to running fits.sh.*

There were recent revisions done to the fits.sh to accommodate other issues.

I just want to make sure that export command resolves the issue in ALL cases.

Thanks again!

Dave B.

**Comment by phebal** [comment]
Thanks again Dave, there's no rush. As far as I can tell, the issue is resolved by setting the LD_LIBRARY_PATH variable. I've tested this with versions 1.0.1 and 1.0.3. I've tested by running fits a hundred times in a row on the same file with no failures. Without the export it'd fail more often then not.
