### ISSUE TITLE
Ubuntu 16.04: Error loading native library for MediaInfo

### ISSUE THREAD

**Issue by jannis701** [harvard-lts/fits#121]
Hi there,

I'm using ubuntu 16.04 and fits 1.0.3 (zip-download). If I run `./fits.sh -i README.md`
I get 
`Exception in thread "main" edu.harvard.hul.ois.fits.exceptions.FitsToolException: Error loading native library for MediaInfo please check that fits_home is properly set`

The file `./tools/mediainfo/linux/libmediainfo.so.0` is in place, I also tried to replace it by the newer version in https://mediaarea.net/download/binary/libmediainfo0/0.7.89/libmediainfo0v5_0.7.89-1_amd64.xUbuntu_16.04.deb but nothing changed.

Is it a bug or am I missing something?

greets
Jannis

**Comment by dbirtwell** [comment]
Jannis:

Note: Ubuntu is not officially supported and is not supported out of the box. However, with a little work, FITS should be able to be be configured to use any 64-bit LINUX version. The one distributed by default is for CentOS/Red Hat. I have tested it with Ubuntu 14.04.2 in the past, but not recently,

A few details on configuring for Ubuntu (or any other 64-bit LINUX):

1) The Ubuntu version of the necessary MediaInfo libraries (not just the MediaInfo library) must reside in the following location:

<FITS_installation>/tools/mediainfo/linux

The 2 files which need to go there are libmediainfo.so.0 and ibzen.so.0

as detailed on the FAQ page:

http://projects.iq.harvard.edu/fits/fitsfaq

2) The supported version of MediaInfo for FITS is 0.7.75. There are details of how to get these libraries on the FAQ page. Unfortunately, the distribution is sometimes an installation package for some LINUX versions and you need to manually unpack the distribution and gram the needed files ... not install the distribution.

3) All other versions of Media Info must be removed from the machine running FITS so there are no conflicts.

If this doesn't work, you can try the following:

* export LD_LIBRARY_PATH=/var/www/apps/fits-1.0.3/tools/mediainfo/linux prior to running fits.sh.*

4) If none of the above work and you don't need Video support, you can comment out the MediaInfo tool all together.

This can be done by commenting out the following line in the FITS xml configuration file which lives in /xml/fits.xml

    <tool class="edu.harvard.hul.ois.fits.tools.mediainfo.MediaInfo" include-exts="avi,mov,mpg,mpeg,mkv,mp4,mxf,ogv,mj2,divx,dv,m4v,m2v,ismv,m2ts,mpeg4" classpath-dirs="lib/mediainfo" />

Please let me know if any of the above solve your problem.

Thanks,

Dave B.

**Comment by jannis701** [comment]
thank you for the quick and detailed reply!
I don't have any version of media-info installed on my system.
I already tried to replace the mediainfo libraries, but for ubuntu16.04 there is only v0.7.89 available, which does not work. using v0.7.75 (for ubuntu 15.04) also did not work....

**but your point 3) does fix the problem! even with the shipped libmediainfo-file.**

point 4) also works as a workaround, of course loosing mediainfo-support....

thank you very much

**Comment by gnosisgithub** [comment]
I needed to comment out:
This can be done by commenting out the following line in the FITS xml configuration file which lives in /xml/fits.xml

But would obviously like to run mediainfo. How can I resolve this issue and run mediainfo?  Thanks.

**Comment by dbirtwell** [comment]
gnosisgithub:

Please provide some more details so we have some more to go on to help you.

What OS and version are you attempting to run FITS on?

What version of Java are you using (NOTE: Oracle Java JDK/JRE is only supported)?

Are both the OS and Java versions used 64-bit (only 64-bit OS and JRE combination is supported)?

Did you read the FITS FAQ first (just checking that you know the supported OSes. We cannot support other than the OSes listed on that page):

http://projects.iq.harvard.edu/fits/fitsfaq

Please also give us a stacktrace if possible.

Getting the MediaInfo Library to load can sometimes be tricky with other than what is supported out of the box.

Also, if you are using a LINUX - CentOS, RedHat or Ubuntu (which is not "officially supported), try the below:
 [ Map to your installtion]

export LD_LIBRARY_PATH=/var/www/apps/fits-1.0.3/tools/mediainfo/linux 
prior to running fits.sh.*

Thanks,

Dave B.

**Comment by gnosisgithub** [comment]
Tired on Windows 7. Does it work on Windows 7?  I tried with version 1.0.3, 1.03, 1.0.2, 1.0.0, etc

JRE 7

32 bit workstation.   I see now that this only works with 64 bit, so I will put together a 64 bit workstation and retry. Thank you!

**Comment by darrenleeweber** [comment]
No problem with fits-1.1.x on Ubuntu 16.04, i.e.

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

$ ls -l /usr/local/bin/fits.sh 
lrwxrwxrwx 1 root root 29 May  2 10:07 /usr/local/bin/fits.sh -> /usr/local/fits-1.1.0/fits.sh*

$ /usr/local/bin/fits.sh -i /usr/local/fits-1.1.0/README.md 
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd" version="1.1.0" timestamp="5/2/17 3:34 PM">
  <identification>
    <identity format="Plain text" mimetype="text/plain" toolname="FITS" toolversion="1.1.0">
      <tool toolname="Jhove" toolversion="1.16" />
      <tool toolname="file utility" toolversion="5.25" />
    </identity>
  </identification>
  <fileinfo>
    <size toolname="Jhove" toolversion="1.16">5232</size>
    <filepath toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">/usr/local/fits-1.1.0/README.md</filepath>
    <filename toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">README.md</filename>
    <md5checksum toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">c1c9cf2a4be3845c2497f82fddb16e64</md5checksum>
    <fslastmodified toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">1493670092000</fslastmodified>
  </fileinfo>
  <filestatus>
    <well-formed toolname="Jhove" toolversion="1.16" status="SINGLE_RESULT">true</well-formed>
    <valid toolname="Jhove" toolversion="1.16" status="SINGLE_RESULT">true</valid>
  </filestatus>
  <metadata>
    <text>
      <linebreak toolname="Jhove" toolversion="1.16" status="SINGLE_RESULT">LF</linebreak>
      <charset toolname="Jhove" toolversion="1.16">US-ASCII</charset>
    </text>
  </metadata>
  <statistics fitsExecutionTime="942">
    <tool toolname="MediaInfo" toolversion="0.7.75" status="did not run" />
    <tool toolname="OIS Audio Information" toolversion="0.1" status="did not run" />
    <tool toolname="ADL Tool" toolversion="0.1" status="did not run" />
    <tool toolname="VTT Tool" toolversion="0.1" status="did not run" />
    <tool toolname="Droid" toolversion="6.1.5" executionTime="217" />
    <tool toolname="Jhove" toolversion="1.16" executionTime="845" />
    <tool toolname="file utility" toolversion="5.25" executionTime="836" />
    <tool toolname="Exiftool" toolversion="10.00" executionTime="821" />
    <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" status="did not run" />
    <tool toolname="OIS File Information" toolversion="0.2" executionTime="136" />
    <tool toolname="OIS XML Metadata" toolversion="0.2" status="did not run" />
    <tool toolname="ffident" toolversion="0.2" executionTime="733" />
    <tool toolname="Tika" toolversion="1.10" executionTime="615" />
  </statistics>
</fits>
```
