### ISSUE TITLE
Name conflict with "Flexible Image Transport System (FITS)"

### ISSUE THREAD

**Issue by darrenleeweber** [harvard-lts/fits#134]
https://en.wikipedia.org/wiki/FITS

Just curious about project commentary about this naming conflict (acronym conflict really).  I came across it while trying to use debian tools to install this project, but debian has the other project under a package called `fitsverify`.

**Comment by randystern** [comment]
Hi Darren,

Yes, we’ve been aware of this for a long time, but the name “FITS” has a lot of recognition in the digital repository space (hundreds of downloads), there is a lot of internal documentation that has the name “FITS” built in, and so we’ve decided not to change it for the time being.

Randy
