### ISSUE TITLE
Problem with Mediainfo Plugin

### ISSUE THREAD

**Issue by kdantas** [harvard-lts/fits#139]
Hi, I don´t know what is happening of wrong with mediainfo plugin in ruTorrent/rTorrent seedbox running in Ubuntu 16.04 Server. Some video files don´t show any information. The same video files in Windows OS open in the mediainfo normally. Somebody can help with this issue?

![image](https://cloud.githubusercontent.com/assets/19543277/26525599/7029432e-4332-11e7-9aac-ebc86cb010ae.png)

**Comment by daveneiman** [comment]
There is information on using MediaInfo on the Fitstool.org [FAQ page](fitstool.org/fitsfaq) if you scroll down to "Video Support Details". In particular:

Out of the box, the FITS MediaInfo tool will ONLY be supporting the following 64-bit OSes: 
- Windows 7, or higher - 64-bit (only tested with Windows 7)
- Mac OS - 64-bit
- Red Hat 6 x86_64 - 64-bit
