### ISSUE TITLE
Tika org.jdom.IllegalAddException in FITS 1.1.1

### ISSUE THREAD

**Issue by RvanVeenendaal** [harvard-lts/fits#141]
Hi,
When running FITS1.1.1, an org.jdom.IllegalAddException from Tika is caught, see below.
FITS is running in a 64-bit Windows 8.1 Enterprise environment, on an Intel Core Duo CPU @1.86Ghz, with 4GB RAM.
In the example below, FITS is started from a USB drive, but the same exception is caught when started from hard drive.
Any suggestions for a solution?
Regards,
Remco

D:\fits-1.1.1>fits.bat  -i "d:\test" -o d:\fits-output -r
2017-06-01 15:30:22 - ERROR - ToolBase:274 - Caught Throwable running tool: Tika
Tool
org.jdom.IllegalAddException: The Element cannot be added to itself
        at org.jdom.ContentList.add(ContentList.java:216)
        at org.jdom.ContentList.add(ContentList.java:131)
        at java.util.AbstractList.add(Unknown Source)
        at org.jdom.Element.addContent(Element.java:811)
        at edu.harvard.hul.ois.fits.tools.tika.TikaTool.buildFileInfoElement(TikaTool.java:599)
        at edu.harvard.hul.ois.fits.tools.tika.TikaTool.buildToolData(TikaTool.java:505)
        at edu.harvard.hul.ois.fits.tools.tika.TikaTool.extractInfo(TikaTool.java:446)
        at edu.harvard.hul.ois.fits.tools.ToolBase.run(ToolBase.java:268)
        at java.lang.Thread.run(Unknown Source)

**Comment by daveneiman** [comment]
Hello,
This section of code has not changed in quite some time. What type of file are you processing with FITS? Could you try it on earlier version(s) of FITS to see if the error still exists. This would help to narrow down the problem.
Thanks.

**Comment by RvanVeenendaal** [comment]
Hi,
Thanks for the quick reply.
I’ve tested the individual files.
The problem is caused by a 39 MB .pst mailbox.
The exception occurs and Apache Tika’s status in the statistics section of the resulting FITS XML is “failed”.
So, is this FITS-related, or Tika?
Regards,
Remco



Van: David Neiman [mailto:notifications@github.com]
Verzonden: donderdag 1 juni 2017 16:01
Aan: harvard-lts/fits
CC: Veenendaal, Remco van; Author
Onderwerp: Re: [harvard-lts/fits] Tika org.jdom.IllegalAddException in FITS 1.1.1 (#141)


Hello,
This section of code has not changed in quite some time. What type of file are you processing with FITS? Could you try it on earlier version(s) of FITS to see if the error still exists. This would help to narrow down the problem.
Thanks.

**Comment by daveneiman** [comment]
Hi again,

Uncertain if this is caused by Tika. What I can indicate is that FITS does provide metadata for .pst files. Sorry.

**Comment by pwinckles** [comment]
This bug was resolved here:

https://github.com/harvard-lts/fits/pull/238/files#diff-fccc4ab64138622c89073ec32b7ca0d66daf22e2d75dc4d05d977d8ed03dc790L606
