### ISSUE TITLE
Feature request: Support STDIN (and STDOUT) on command line

### ISSUE THREAD

**Issue by atz** [harvard-lts/fits#142]
Examples:
```bash
fits.sh <myFileToProcess.pdf >theOutput.txt

my_file_streamer --id=1234 | fits.sh | my_fits_uploader --id=1234
```

*Ideally* the file itself never has to hit disk, though if underlying tools require it, tempfile storage would be expected.

**Comment by atz** [comment]
This seems to relate to #26

**Comment by daveneiman** [comment]
As there is currently no official dedicated FITS support, it would be great to suggest a feature through a pull request. Thanks.
