### ISSUE TITLE
Exiftool cannot identify epubs if Archive::Zip perl module is not installed

### ISSUE THREAD

**Issue by aelkiss** [harvard-lts/fits#143]
Platform: Debian 8 (jessie)
FITS version: 1.0.7

FITS reports e.g.

```xml
  <identification status="CONFLICT">
    <identity format="EPUB" mimetype="application/epub+zip" toolname="FITS" toolversion="1.0.7">
      <tool toolname="Droid" toolversion="6.1.5" />
      <tool toolname="Tika" toolversion="1.10" />
      <externalIdentifier toolname="Droid" toolversion="6.1.5" type="puid">fmt/483</externalIdentifier>
    </identity>
    <identity format="EPUB" mimetype="application/zip" toolname="FITS" toolversion="1.0.7">
      <tool toolname="Exiftool" toolversion="10.00" />
    </identity>
  </identification>
```

The bundled exiftool reports: 
` <ExifTool:Warning>Install Archive::Zip to decode compressed ZIP information</ExifTool:Warning>`

Installing `Archive::Zip` for the system perl (e.g. `apt-get install libarchive-zip-perl`) changes the results to:

```xml
  <identification>
    <identity format="EPUB" mimetype="application/epub+zip" toolname="FITS" toolversion="1.0.7">
      <tool toolname="Droid" toolversion="6.1.5" />
      <tool toolname="Exiftool" toolversion="10.00" />
      <tool toolname="Tika" toolversion="1.10" />
      <externalIdentifier toolname="Droid" toolversion="6.1.5" type="puid">fmt/483</externalIdentifier>
    </identity>
  </identification>
```

Suggested fix: FITS should bundle Archive::Zip (if possible) or document it as a dependency (if not)

**Comment by daveneiman** [comment]
Hi,
Since our development resources a very limited, it would be wonderful if you could fork the FITS project, make your suggested change, run the existing tests and possibly add more tests that include additional EPUB files. If all this succeeds then create a pull request.
Thanks for considering this.

**Comment by aelkiss** [comment]
@jmcglone @sethaj Do either of you have any interest in looking into this more? Given the known workaround it seems like a pretty low priority.
