### ISSUE TITLE
Tried to set read limit but seems to take the same amount of time.

### ISSUE THREAD

**Issue by emchen11** [harvard-lts/fits#145]
FITS version: 1.1.1

Changed xml file to set read limit on mov files, tested it on a large mov file (~25GB) and

before read limit:
<statistics fitsExecutionTime="856877">

after read limit:
<statistics fitsExecutionTime="860332">

This doesn't seem right, what kind of difference should I be expecting to see?

**Comment by daveneiman** [comment]
Something is missing from you post after the "before read limit:" and "after read limit:" text.
Keep in mind that this configuration is purely optional and is intended solely to increase processing speed. If you do not like the results you have the option of either modifying the file extension list and read-limit value or just keeping these values commented-out for full file processing.

**Comment by emchen11** [comment]
Sorry I meant to put in how long it took for the file to process before I uncommented the read limit and after. Basically it took the same amount of time (in fact slightly longer) so I was wondering if I was doing something wrong or misunderstanding how I was meant to utilise this feature. For reference this is how I edited the xml file:

> 	
	<droid_sigfile>DROID_SignatureFile_V82.xml</droid_sigfile>
	
	
	<droid_read_limit include-exts="mov,mxf" read-limit-kb="64" />

**Comment by daveneiman** [comment]
Yes, your edit looks correct. Please keep in mind that, with this optional configuration, sometimes you may not get the desired Droid output. Though it was meant for our internal use for certain types of very large files, we decided to make it public. Take a look at Droid message boards for discussion on this topic.
