### ISSUE TITLE
Missing input file should not show a stack trace.

### ISSUE THREAD

**Issue by jcoyne** [harvard-lts/fits#146]
A stack trace is helpful for a programmer, but typically confusing for a user. 

Current behavior:
```
fits.sh -i foo.pdf
Jun 30, 2017 9:41:19 AM edu.harvard.hul.ois.jhove.JhoveBase init
SEVERE: Testing SEVERE level
Exception in thread "main" edu.harvard.hul.ois.fits.exceptions.FitsConfigurationException: foo.pdf does not exist or is not readable
	at edu.harvard.hul.ois.fits.Fits.examine(Fits.java:522)
	at edu.harvard.hul.ois.fits.Fits.doSingleFile(Fits.java:405)
	at edu.harvard.hul.ois.fits.Fits.main(Fits.java:291)
```

Suggested behavior:
```
fits.sh -i foo.pdf
Unable to open image 'foo.pdf': File does not exist or is not readable.
```

**Comment by daveneiman** [comment]
Thanks for the suggestion. This brings up the question as to what other better messages could be displayed when exceptions are thrown for other scenarios. This, in part, involves discussion with our internal users of FITS. Unfortunately, we do not have resources to address this issue at this time. Please feel free to fork the code and make necessary change and possibly generate a pull request. Thanks!

**Comment by pwinckles** [comment]
In the forthcoming release, if the FITS cli exits with an exception it will not log the stack trace by default. This behavior can be changed with the `-d` flag. Additionally, if you don't want exceptions logged to the console at all, then you can edit your `log4j2.xml` and change the `Pattern` for the `CONSOLE` appender to look like:

```
<Pattern>%d{yyyy-MM-dd HH:mm:ss} - %5p - %c{1}:%L - %m%n%throwable{none}</Pattern>
```
