### ISSUE TITLE
Github release zip files do not contain fits.jar

### ISSUE THREAD

**Issue by jcoyne** [harvard-lts/fits#149]
With 1.2.0-RC1
```
fits-1.2.0-RC1/fits.sh -i "test.png"
Error: Could not find or load main class edu.harvard.hul.ois.fits.Fits
```

```
java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
```

On OSx 10.12

**Comment by jcoyne** [comment]
Ah, this is due to using the zip  files from github release pages.  These do not have the Fits jar files in them.  Perhaps look at: https://github.com/harvard-lts/fits/issues/62#issuecomment-226233317

**Comment by daveneiman** [comment]
Github is for obtaining the source if you'd like to build your own or fork the repo. The executables can be downloaded from the FITS website here: http://fitstool.org

**Comment by jcoyne** [comment]
@daveneiman the problem I have is that these pages have download links for zipfiles and there's nothing that indicates to the user that they don't work: https://github.com/harvard-lts/fits/releases/tag/1.2.0-RC1

**Comment by daveneiman** [comment]
The links on that page indicate "Source code", with no indication they are binaries. This appears to be the way Github shows its Tag pages. Also, in the README.md right at the top is a reference to the downloads page.

**Comment by jcoyne** [comment]
I understand that if you don't post your binaries, you're fighting against github and the habits of users who are accustomed to downloading other projects from github.  Perhaps one way to handle this is to have `fits.sh` or `fits-env.sh` raise an error if `fits.jar` isn't on the classpath.  Something like "You haven't compiled fits.sh" rather than the rather esoteric "Could not find or load main class edu.harvard.hul.ois.fits.Fits"

**Comment by daveneiman** [comment]
Great idea! Feel free to fork the code, make the enhancement and generate a pull request. It would be most welcome.

**Comment by daveneiman** [comment]
Yes, I'm getting the same error on all attempts to download ZIP files. Will look into this issue via IT support as this hasn't been a problem in the past. My apologies that this is occurring.

**Comment by daveneiman** [comment]
This issue now appears to be resolved. Please try again and, if it still doesn't work, let us know in a NEW issue with a relevant topic (not this one). Thanks.
