### ISSUE TITLE
FITS 0.6.2 - versions of JHove, Droid used within it

### ISSUE THREAD

**Issue by VickyPhillips** [harvard-lts/fits#15]
Hello,
What is the current version of JHove and Droid used within FITS 0.6.2?  We are currently looking at Archivematica (v 0.10) which has version 0.6.1 built in.  Looking at the output it looks like we have JHove 1.5 and Droid 3.0 although JHove 1.11 and Droid 6.1.3 are available.  Also looking at the release notes on the following page http://code.google.com/p/fits/ it doesn't look like JHove has been updated in latest release.  I just wanted to get an idea as to how well FITS keeps up-to-date with new releases of DROID and JHove etc.
Thanks,
Vicky

**Comment by ross-spencer** [comment]
Is there anyone in the community actively doing this now do we know? - In light of the OPF taking over JHOVE support it might be a good opportunity to do this soon.
