### ISSUE TITLE
Publish 1.2.0-RC1 on the website

### ISSUE THREAD

**Issue by jcoyne** [harvard-lts/fits#150]
It would be nice to be able to test the fully packaged release candidate.  If the binary was published at: https://projects.iq.harvard.edu/files/fits/files/fits-1.2.0-RC1.zip, that would be great.

**Comment by daveneiman** [comment]
Sorry, due to very limited resources we only publish binaries of the final releases. Feel free to build your own to test RC's. The RC's are tagged for our own QA process.

**Comment by jcoyne** [comment]
I understand where you're coming from, but you might consider letting the broader open source community help you in your QA process. Many hands make for light work.
