### ISSUE TITLE
Is travis used?

### ISSUE THREAD

**Issue by jcoyne** [harvard-lts/fits#152]
I don't see anything here: https://travis-ci.org/harvard-lts/fits
however there is a `.travis.yml` in the repository.

**Comment by daveneiman** [comment]
Thanks for pointing this out. Will look into it.

**Comment by daveneiman** [comment]
Attempted to get travis to work with FITS. However, due to the nature of some of the tests, was unable to get tests to pass even though they pass during a local build. If/when the project is move to a Maven build this may be revisited.
