### ISSUE TITLE
Q: Specify fits.xml and other config files at runtime?

### ISSUE THREAD

**Issue by jrochkind** [harvard-lts/fits#157]
Is there a way to pass the location of fits.xml and other .xml config at runtime?  So the same fits installation on the same machine can be used with different configuration in different runs?  Any advice?

**Comment by daveneiman** [comment]
Yes, this can be done, but only programmatically, not with the shell script.
Look at the constructor to the file edu.harvard.hul.ois.fits.Fits.java:
public Fits( String fits_home, File fitsXmlConfig )

You can programmatically call this constructor to set the specific location of the fits.xml file you'd like to use. An example for this usage is in several test classes.
In the 'tests' directory take a look at the file edu.harvard.hul.ois.fits.junit.AdobeIllustratorXmlTest.java in the method beforeClass().

From there you would use the API in the Fits class: examine(File) to process a single file.

**Comment by jrochkind** [comment]
Thanks! I guess I could try to write my own wrapper that would give me a command line interface similar to the shell script, but which allowed specification on command line?

Would it make sense to make this a feature request for the standard shell script?

How about fits_format_tree.xml and other .xml config files?

**Comment by daveneiman** [comment]
Perhaps you could add to the parameter list by giving an optional location of the fits.xml file. I'm not sure about adding the relocation of the entire XML directory outside of "FITS_HOME". Feel free to add a feature request. However, it would likely be accomplished more quickly if you contributed the work via a Git pull request.

**Comment by jrochkind** [comment]
OK, thanks. I know only a bit of Java, I think I see an easy way to at least add the fits.xml as a command-line argument maybe... but I'm not actually sure how to compile or run tests (if any) on the project (sorry, I am not really a Java dev).  Is there any docs on this for this project? Sorry if they're there somewhere I haven't been able to find!

**Comment by daveneiman** [comment]
@jrochkind - It was fairly easy to add your request. I've committed a GitHub branch which I'm requesting you try to see if it works for you. You will need to build FITS with the Ant tool first. The new command line parameter is -f followed by the path to the fits.xml configuration file. Testing this would be a big help. Thanks.  Here is the GitHub branch to checkout:
https://github.com/daveneiman/fits/tree/parameterize_fits_config
