### ISSUE TITLE
Caught exceptions never recorded in Fits.examine()

### ISSUE THREAD

**Issue by dmolesUC3** [harvard-lts/fits#159]
The `caughtExceptions` list in `Fits.examine()` is [initialized](https://github.com/harvard-lts/fits/blob/dev/src/edu/harvard/hul/ois/fits/Fits.java#L531) and [reported](https://github.com/harvard-lts/fits/blob/dev/src/edu/harvard/hul/ois/fits/Fits.java#L600), but apparently never populated.

**Comment by daveneiman** [comment]
Right you are! Perhaps this a relic from the past. Will make a note to examine in a future release.
Good catch. :)

**Comment by daveneiman** [comment]
This collection will be populated in the upcoming release. When there is an error/exception from within one of the tools that FITS aggregates, in addition to a `status="failed"` for the tool in the output file, the error will now be logged via Log4j.
