### ISSUE TITLE
FITS Binaries don't download

### ISSUE THREAD

**Issue by jonathangreen** [harvard-lts/fits#163]
When I try to download FITS binaries for example: 
https://projects.iq.harvard.edu/files/fits/files/fits-1.2.0.zip

The file partially downloads, then I get a server error. Seems like there are some server side issues? Would it be possible to either put the release binaries on GitHub or perhaps fix the server so the downloads work again? 

This is causing FITs to fail to install in this playbook: 
https://github.com/Islandora-CLAW/CLAW/issues/747

The current solution is just to not use FITS, but I'd like to be able to use FITS :)

**Comment by daveneiman** [comment]
We're sorry about this issue. Our IT department is working on resolving this for the second time. Unfortunately, the FITS ZIP file exceeds the maximum file upload size for GitHub. My recommendation is to clone or download the project and build it.

**Comment by daveneiman** [comment]
Due to recent server issues, FITS downloads have been failing. As a temporary work-around, the latest FITS binaries have been put on an alternate site so that they may be downloaded until this problem is resolved. The download link for fits-1.2.0.zip on the downloads page has been updated.

**Comment by daveneiman** [comment]
Server issue has been fixed and binaries are now able to be downloaded from the fitstool.org site [here](https://projects.iq.harvard.edu/fits/downloads).

**Comment by jonathangreen** [comment]
Thank you @daveneiman
