### ISSUE TITLE
only validate option

### ISSUE THREAD

**Issue by florianajir** [harvard-lts/fits#17]
First of all, thank's for this good work on FITS development. 

I recently discover this tool and I use it to know if a file is valid but I don't need to fetch all metadata infos. 

Can you tell me if it's possible to plan a new option in further developments to output a result like a boolean for exemple to just say if the file is ok ?

There are any others validation tools include in FITS to validate formats unkown by JHOVE ?

Thank you all for your work and open source devotion

**Comment by daveneiman** [comment]
Sorry, no plans for just validation.
