### ISSUE TITLE
Odf and office files validation

### ISSUE THREAD

**Issue by florianajir** [harvard-lts/fits#18]
Do you plan to add validation for formats like OpenOffice (odt, odp, ods, etc.) and Microsoft Office (doc, docx, etc.) ?

I know there are java tools like ODF VALIDATOR wich you could include in your program.
http://incubator.apache.org/odftoolkit/conformance/ODFValidator.html

Or maybe FITS can even detect errors in that kind of files ?

**Comment by daveneiman** [comment]
FITS, since v.1.0.0, handles word processing documents such as .doc, .docx, .odt, etc.
https://projects.iq.harvard.edu/fits/news/fits-100-and-fits-service-112-released
