### ISSUE TITLE
FITS web service character encoding issue

### ISSUE THREAD

**Issue by pautri** [harvard-lts/fits#186]
When using FITS as a web service, the XML output may contain invalid characters (and therefore the XML as a whole is invalid). We ran into this with a PDF file that was produced using Microsoft Word 2010. The Jhove "creatingApplicationName" field contains the value "Microsoft® Word 2010/Microsoft® Word 2010" when running FITS from the command line, but this ® is transformed into a non-valid character when running FITS as a web service.

**Comment by daveneiman** [comment]
There will be a new release of the [FITS Service project](https://github.com/harvard-lts/FITSservlet/tree/master) (is this what you are using to run FITS?) within the next day. In our testing we discovered that the character encoding of the response was 8859-1 which was causing the same problem during our test cycle. Changing the response character encoding to UTF-8 resolved this problem. If you are using your own web service please ensure that your response also does the same. Let us know how it goes.

**Comment by pautri** [comment]
Thanks Dave, I installed the 1.2.0 release of the FITS Service project and the issue is indeed solved.
