### ISSUE TITLE
README and Quick start out of date?

### ISSUE THREAD

**Issue by LibrarPotter** [harvard-lts/fits#192]
I am installing and running FITS for the first time, and I've run into several errors and issues.  One is that the README and the [Quickstart Guide](https://projects.iq.harvard.edu/fits/get-started-using-fits) indicate the presence of a file called "RELEASE.txt" which does not appear to be included in any of the three releases I've tried (1.3.0, 1.4.0, and 1.4.1).  
On its own this isn't a problem, I simply tried to use a different file to test.  Now I am running into many Java errors, which start with: Exception in thread "main" java.lang.UnsupportedClassVersionError --- etc.  I have Java version 1.7.0_80

With the lack of a RELEASE.txt file and the issues I'm running into, I am wondering if the instructions in the Quickstart guide are out dated since some substantial changes may have happened.  For example, should I now be compiling the tool?  

UPDATE:
FITS-1.3.0 is working, but neither 1.4.0 nor 1.4.1 is.

Thank you!

**Comment by daveneiman** [comment]
Hello,
Yes, the README.md file is a bit outdated. Thanks for pointing this out. We will create a ticket to fix this in a future release. As you figured out, another file can be used in place of RELEASE.txt which no longer exists. There are release notes. They now are located in GitHub here:
https://github.com/harvard-lts/fits/wiki/FITS-Releases-Notes

The Java version problem appears to be more serious and we will prioritize this issue. The executable code is built to a Java 1.7 target so should run on both 1.7 and 1.8.
However, please try to build the project after cloning the project from GitHub. The Maven build tool is required. The command to build the final ZIP file would be:
`$ mvn package -DskipTests`

If you don't mind, let us know how it goes.

Thanks!

**Comment by pwinckles** [comment]
FITS is actually built to Java 1.8: https://github.com/harvard-lts/fits/blob/dev/pom.xml#L17

You need Java 1.8 or higher to run FITS.
