### ISSUE TITLE
Wrong tika jar in 1.4.1 release?

### ISSUE THREAD

**Issue by jenswegar** [harvard-lts/fits#193]
The release notes for version 1.4.1 say the Tika tool was updated, and the pom.xml diff shows that the version was bumped to 1.20 from 1.19.1 (https://github.com/harvard-lts/fits/commit/350c86c44770516a6ab828ca30699aee7b0cabaf). However, when I run an analysis after having updated to version 1.4.1, the xml-output says tool version used is still 1.19.1:

```
<statistics fitsExecutionTime="1312">
        <tool toolname="MediaInfo" toolversion="0.7.75" status="did not run" />
        <tool toolname="OIS Audio Information" toolversion="0.1" status="did not run" />
        <tool toolname="ADL Tool" toolversion="0.1" status="did not run" />
        <tool toolname="VTT Tool" toolversion="0.1" status="did not run" />
        <tool toolname="Droid" toolversion="6.4" executionTime="1041" />
        <tool toolname="Jhove" toolversion="1.20.1" executionTime="1298" />
        <tool toolname="FileUtility" toolversion="[unknown]" status="failed" />
        <tool toolname="Exiftool" toolversion="[unknown]" status="failed" />
        <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" status="did not run" />
        <tool toolname="OIS File Information" toolversion="0.2" executionTime="842" />
        <tool toolname="OIS XML Metadata" toolversion="0.2" status="did not run" />
        <tool toolname="ffident" toolversion="0.2" status="did not run" />
        <tool toolname="Tika" toolversion="1.19.1" executionTime="1172" />
</statistics>
```

I checked the master branch, and the ```lib/tika``` folder still has the ```tika-app-1.19.1.jar``` from 6 months ago. Something I'm missing in how the build process works, or was the jar actually not updated in the latest release?

**Comment by daveneiman** [comment]
Hello,
Thanks for pointing this out. In fact the release notes are correct in that Tika 1.19.1 is included in the latest release of FITS. Though the POM does indicate 1.20 for Tika, the dependency stanza for Tika contains the element `<scope>provided</scope>` which means that version 1.20 is only provided for compilation resolution but not included in the final build. There is a more involved explanation for this what has to do with a custom class loader included with the application which can be addressed in another discussion. Thus, it is the 1.20 in the POM that is in error and was mistakenly added to the latest release. This 1.20 version of Tika will be included in the next release.
Thank you,
The FITS development team
