### ISSUE TITLE
JHOVE outputs non-XML content to stdout for certain files

### ISSUE THREAD

**Issue by mistydemeo** [harvard-lts/fits#20]
When FITS's embedded JHOVE is enabled, certain files will print non-XML content to stdout. For example, here's the first five lines when running on [`balloon_eciRGBv2_ps_adobeplugin.jpf`](https://github.com/openplanets/format-corpus/raw/master/jp2k-test/icc/balloon_eciRGBv2_ps_adobeplugin.jpf) from the [OPF format corpus](https://github.com/openplanets/format-corpus):

``` xml
READBOX seen=true
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd" version="0.8.2" timestamp="15/09/14 10:00 AM">
  <identification>
    <identity format="JPEG 2000 JP2" mimetype="image/jp2" toolname="FITS" toolversion="0.8.2">
```

Since the first line isn't valid XML, anything that attempts to parse FITS's output as XML will fail.

This doesn't happen when JHOVE is disabled in the FITS configuration file, so the problem appears to be coming from the embedded version of JHOVE specifically.

**Comment by jcoyne** [comment]
@mistydemeo I'm running into this now.  Did you figure out something?

**Comment by ross-spencer** [comment]
Is it happening with the same files in standalone versions of JHOVE? - Has it been fixed in more recent versions of the tool?

**Comment by daveneiman** [comment]
Ran this JPF file with FITS 1.2.0 (which contains JHOVE 1.16) and there was no non-XML output to the console.
