### ISSUE TITLE
Configurable DROID signature files, and output of signature file versions used

### ISSUE THREAD

**Issue by ross-spencer** [harvard-lts/fits#22]
Hi,

I'm trying to baseline FITS to see which versions of external tools are currently incorporated and what the fits output looks like. Specifically I am interested in DROID, at first, as this is the primary form of identification my current tools are based on. 

What I believe to be the case is that FITS is using DROID 6.1.3, but the container identification mechanism isn't called, or at the same version as the original. 

I am able to test DROID container identification using a test-suite of skeleton objects, matching the version that is packaged with DROID 6.1.3:

https://github.com/exponential-decay/skeleton-container-test-suite-generator/blob/master/skeleton-container-suite-20130501.zip

01-05-2013. 

The zip based objects are mostly identified as ZIP objects, and OLE2 based objects, OLE2 where there isn't a standard signature. 

Looking at the configuration options for FITS it seems that you might use an old DROID configuration file (DROID_config.xml), and you've no mechanism to configure which container signature file is used, only the version of standard signature file within fits.xml

Improving support for this mechanism of identification would be incredibly useful.

Happy to provide more info as required.

Thanks,

Ross

**Comment by anjackson** [comment]
I just noticed that [FITS is only using the BinarySignatureIdentifier](https://github.com/harvard-lts/fits/blob/master/src/edu/harvard/hul/ois/fits/tools/droid/DroidQuery.java#L40). I also had to deal with this when developing [Nanite](https://github.com/openpreserve/nanite) (an embeddable version of the DROID identification engine), so I thought I'd outline my approach here, in case it helps.

I solved it by cloning some of the code and logic from DROID. It was rather clumsy, as it also involved [extending classes in the uk.gov.nationalarchives.droid.core package](https://github.com/openpreserve/nanite/tree/master/nanite-core/src/main/java/uk/gov/nationalarchives/droid/core), and in particular, making a [CustomResultPrinter](https://github.com/openpreserve/nanite/blob/master/nanite-core/src/main/java/uk/gov/nationalarchives/droid/core/CustomResultPrinter.java) that allows the container-level ID result to be extracted. You can see the overall logic in the [DroidDetector](https://github.com/openpreserve/nanite/blob/master/nanite-core/src/main/java/uk/bl/wa/nanite/droid/DroidDetector.java) class, which wraps DROID up to conform to the Apache Tika format identification interface.

**Comment by pwinckles** [comment]
Resolved by https://github.com/harvard-lts/fits/pull/275
