### ISSUE TITLE
fits_output.xsd schema - no root element found

### ISSUE THREAD

**Issue by tw4l** [harvard-lts/fits#220]
The fits_output.xsd schema at http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd appears to be missing or broken.

When I navigate to that page in my browser, I see the following error:

```
XML Parsing Error: no root element found
Location: http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd
Line Number 1, Column 1:
```

This is also causing downstream Jhove issues in Archivematica at the moment, with the same error message as the browser.

**Comment by daveneiman** [comment]
Hello,
The location of this schema has now been fixed with a redirect to its current location.
Please let us know if this fix works for you.
Thanks!
