### ISSUE TITLE
404 Not Found: targetNamespace="http://hul.harvard.edu/ois/xml/ns/fits/fits_output"

### ISSUE THREAD

**Issue by bradspry** [harvard-lts/fits#24]
404 Not Found:
targetNamespace="http://hul.harvard.edu/ois/xml/ns/fits/fits_output"
xmlns:fits="http://hul.harvard.edu/ois/xml/ns/fits/fits_output"

**Comment by DaveSiegel** [comment]
Is this what you're looking for? 

http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd

**Comment by bradspry** [comment]
@DaveSiegel my expectation was for the URI (http://hul.harvard.edu/ois/xml/ns/fits/fits_output) to resolve successfully, but now I believe, in this case, it just represents a unique identifier.

Thank You for your time!

**Comment by bradspry** [comment]
Please close this issue at your earliest convenience.
