### ISSUE TITLE
About 1.5.1 release

### ISSUE THREAD

**Issue by chenrui333** [harvard-lts/fits#243]
:wave: it looks like the 1.5.1 release was not properly done (i.e. it did not include the `fits-1.5.1.zip` artifact), let me know if that makes sense. Thanks!

**Comment by daveneiman** [comment]
FITS 1.5.1 will be officially release this coming week. So far it has been tagged but please note there there is nothing in the Release page yet.

**Comment by chenrui333** [comment]
Yeah, I saw the tag and just curious about the formal release. Thanks for confirming it!
