### ISSUE TITLE
Update logging to Log4j2 from Log4j1

### ISSUE THREAD

**Issue by daveneiman** [harvard-lts/fits#244]
Or possibly some logging wrapper (slf4j, etc.) that may account for log4j 1 which may be in use inside one or more of the aggregated tools.

**Comment by preserve-cat** [comment]
Woohoo. Thank you!

**Comment by pwinckles** [comment]
For reference, @bbpennel just did the work upgrade to slf4j+log4j2 in our fork: https://github.com/UW-Madison-Library/fits/pull/2

**Comment by bbpennel** [comment]
Similarly, this branch would update the FITSservlet project, although it is also referencing the UW-Madison fork for the moment:
https://github.com/harvard-lts/FITSservlet/compare/master...bbpennel:log4j2

**Comment by awoods** [comment]
Is this issue being worked?

**Comment by pwinckles** [comment]
resolved by https://github.com/harvard-lts/fits/pull/268
