### ISSUE TITLE
Update MediaInfo to latest version

### ISSUE THREAD

**Issue by daveneiman** [harvard-lts/fits#249]
There are many versions of MediaInfo so the proper version will need to be selected for inclusion.
Code and tests will likely need to be updated if raw tool output has changed.

**Comment by kieranjol** [comment]
Aye, a new schema has been introduced since the version included in current FITS

**Comment by daveneiman** [comment]
I made an attempt quite some time ago to accommodate this new schema. Given the time required I needed to stop so I could get back to more urgent work.

**Comment by pwinckles** [comment]
It is possible to use the old schema with the new library, as demonstrated in this PR: https://github.com/harvard-lts/fits/pull/209

**Comment by pwinckles** [comment]
MediaInfo was upgraded to 20.08 in this PR https://github.com/harvard-lts/fits/pull/209. However, the latest version is 21.09.

@sprater was going to try to get a decent build of 21.09 for this upgrade.
