### ISSUE TITLE
Create plan for porting existing documentation site

### ISSUE THREAD

**Issue by awoods** [harvard-lts/fits#255]
This task is to review the existing [FITS documentation site](https://projects.iq.harvard.edu/fits/home) and establish a potentially multi-phase plan for porting the documentation to a new GH-Pages site.

Related to: 
- https://github.com/harvard-lts/fits/issues/253
- https://github.com/harvard-lts/fits/issues/254

**Comment by mferrarini** [comment]
Setting up a meeting early next week that should influence the direction of this issue.

**Comment by awoods** [comment]
Now that the documentation has been migrated to GitHub-pages, the remainder of this work will be handled under https://github.com/harvard-lts/fits/issues/333 .
