### ISSUE TITLE
Write a mapping of select metadata elements from embARC XML to FITS XML

### ISSUE THREAD

**Issue by bertramlyons** [harvard-lts/fits#259]
Mapping document available here: https://docs.google.com/spreadsheets/d/1o5MVGwbkmRq1oGSWsLSy__7MGt-LSvcbOGicamUX-WE/edit?usp=sharing

**Comment by rwendler** [comment]
I did not meet up with Bert, my fault. I reviewed the spreadsheet but had no comments. I appreciate the work you did on this!

**Comment by pwinckles** [comment]
@bertramlyons can this be closed or is there outstanding work?

**Comment by pwinckles** [comment]
I'm going to close this because I think the embARC work is done. @bertramlyons feel free to comment and reopen if there is something else that needs to be done here.
