### ISSUE TITLE
Look into upgrading JDom to current 2.x version

### ISSUE THREAD

**Issue by daveneiman** [harvard-lts/fits#278]

**Comment by awoods** [comment]
Resolved with: https://github.com/harvard-lts/fits/commit/351db23efa155331f6fede3bd6d4268c138eb3b4

**Comment by pwinckles** [comment]
@awoods That commit is for _log4j2_ not _jdom2_

**Comment by daveneiman** [comment]
Resolved with [e5568db](https://github.com/harvard-lts/fits/commit/37e5568dbbcdd0b87bc81a92fb8b0ff43a786b0d)
