### ISSUE TITLE
Move release notes from wiki to actual releases section for each release (or at least most recent)

### ISSUE THREAD

**Issue by daveneiman** [harvard-lts/fits#302]

**Comment by pwinckles** [comment]
@awoods I'm not sure if we need to do anything here. The releases [releases section](https://github.com/harvard-lts/fits/releases) currently have descriptions.

**Comment by awoods** [comment]
@pwinckles : There are some minor text additions that we can pull from the current project wiki into the GitHub release descriptions. For example:
1. 1.5.5
   - Old: https://projects.iq.harvard.edu/fits/news/fits-155-released
   - New: https://github.com/harvard-lts/fits/releases/tag/1.5.5
 2. 1.5.0
   - Old: https://projects.iq.harvard.edu/fits/news/fits-150-released
   - New: https://github.com/harvard-lts/fits/releases/tag/1.5.0

**Comment by pwinckles** [comment]
Okay, I went through and updated all of the Github release titles to be in the form "Release X.Y.Z", and copied over additional information from the FITS website when appropriate.
