### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by bayandin** [harvard-lts/fits#317]
I'm confused regarding the license that the project uses:
- The repo itself says Apache 2.0: https://github.com/harvard-lts/fits/blob/1.5.2/License.md
- But the website says that it's under LGPL license: https://projects.iq.harvard.edu/fits/code-license

Could you please confirm which license is correct?

**Comment by awoods** [comment]
Hello, @bayandin .
Thanks for raising the inconsistency. Even though Harvard's Library Technology Services team has a preference for Apache 2, given the fact that FITS includes GPL libraries, it would be [incompatible](https://www.apache.org/licenses/GPL-compatibility.html) to release FITS as Apache 2.

See: https://github.com/harvard-lts/fits/pull/318

**Comment by pwinckles** [comment]
@awoods Which component are you referring to? Most of them are LGPL which I don't think will create a problem because it doesn't trigger copyleft for linking. I'm not sure about exiftool. It's an odd one that use the [artistic license](https://en.m.wikipedia.org/wiki/Artistic_License), which I haven't had a chance to read up on yet. If it was a problem, you could certainly avoid the issue by not redistributing exiftool, like I would prefer, and use the system copy. FITS shells out to it.

**Comment by pwinckles** [comment]
[exiftools' license](https://www.exiftool.org/#license), which is the same as [Perl's](https://dev.perl.org/licenses/). I think Perl is using v1 of the [artistic license](https://dev.perl.org/licenses/artistic.html), which seems very permissive.

In the Java ecosystem, the majority of GPL libraries either use LGPL or GPLv2 with a class path exemption. The later is how Java itself is licensed. Neither of these license are copyleft when used via linking. In fact, [it sounds like it is more problematic](https://opensource.stackexchange.com/questions/5664/linking-from-lgpl-2-1-software-to-apache-2-0-library) for a LGPL project to link to an Apache 2 project than the opposite.

**Comment by awoods** [comment]
@pwinckles:
If the [code-license](https://projects.iq.harvard.edu/fits/code-license) page is up to date (which would benefit from verification), we need to consider the inclusion of libraries covering the following licenses:
1. LGPL v2.1
2. GPL or the artistic license ??
3. Apache v1.1, v2
4. BSD v2
5. [BSD style](https://mediaarea.net/en/MediaInfo/License)

The question is, which license can compatibly include libraries with the above licenses. @pwinckles , is your understanding that the answer is "Apache v2"?

**Comment by pwinckles** [comment]
@awoods Yes, obviously not a lawyer, but my understanding is the Apache v2 is the appropriate license to use, and that if this project were instead licensed as LGPL (v2.1 at least; not sure about 3) then it would be incompatible with it's Apache 2 dependencies. But, perhaps you should run it by your legal team?
