### ISSUE TITLE
Logging config regression

### ISSUE THREAD

**Issue by bbpennel** [harvard-lts/fits#33]
It looks like there was a change to the way that logging configuration was looked up, but that change was undone a short time later.

This commit made some changes to the way that the logging configuration was found:
https://github.com/harvard-lts/fits/commit/ae69e7c360a175a6606c3dafc9dd689b4644cf3c#diff-bbd93c99423a6c6e9467a7b61158dd7a

But the change got undone when merging here:
https://github.com/harvard-lts/fits/commit/66c233666c1ff5655dd3272be3e910a91034e23f#diff-bbd93c99423a6c6e9467a7b61158dd7a

I am having difficulty getting log4j to stop throwing warnings about not finding the configuration since it is overriding where the file is located.

**Comment by paulmer** [comment]
Yes, I submitted the patch that converted the log4j configuration file path to the URL which is required by the log4j configuration functions.  I'm not sure why this was undone but the latest code simply prepends "file:" to the file path, and that doesn't seem right.  Would it be possible to reinstate my patch?

**Comment by DaveSiegel** [comment]
The logging patch was reinstated.

**Comment by bbpennel** [comment]
Line 129 no longer has any effect since the property is immediately overridden:
https://github.com/harvard-lts/fits/blob/master/src/edu/harvard/hul/ois/fits/Fits.java#L129
