### ISSUE TITLE
NLNZ Metadata Extractor fails on FLAC (Free Lossless Audio Codec) in FITS 1.6.0

### ISSUE THREAD

**Issue by paul-aloisio** [harvard-lts/fits#373]
When running FITS 1.6.0 on test.flac (in attached zip file) NLNZ threw an error. FITS 1.5.5 was able to process this same file successfully.

[flac_FITS_tests.zip](https://github.com/harvard-lts/fits/files/10279209/flac_FITS_tests.zip)

**Comment by pwinckles** [comment]
@paul-aloisio Thanks for reporting. That error has not affect on the FITS output, but I did put together a PR to fix the issue.
