### ISSUE TITLE
NLNZ Metadata Extractor FileNotFoundException for MP3 on read-only NFS mount

### ISSUE THREAD

**Issue by rstanonik** [harvard-lts/fits#382]
Hi,
We're running the docker FITS on files on a read-only NFS share.  It throws an error for MP3 files.  If I copy the files to a local, writable directory, then no error occurs.  Another test was to copy the file to a local directory and make that read-only, in which case no error occurred, so maybe NFS and read-only is the issue. Below is example output of the error.
Thanks,
Ron

rstanonik@lib-fits:~$ fits.sh -i dams4/bb/00/00/85/4v/20775-bb0000854v-1-1.mp3
java.io.FileNotFoundException: dams4/bb/00/00/85/4v/20775-bb0000854v-1-1.mp3 (Permission denied)
        at java.base/java.io.RandomAccessFile.open0(Native Method)
        at java.base/java.io.RandomAccessFile.open(Unknown Source)
        at java.base/java.io.RandomAccessFile.<init>(Unknown Source)
        at java.base/java.io.RandomAccessFile.<init>(Unknown Source)
        at org.farng.mp3.MP3File.<init>(Unknown Source)
        at org.farng.mp3.MP3File.<init>(Unknown Source)
        at nz.govt.natlib.adapter.jID3LibMp3.ID3TagLibMP3Adapter.adapt(ID3TagLibMP3Adapter.java:89)
        at edu.harvard.hul.ois.fits.tools.nlnz.MetadataExtractor.extractInfo(MetadataExtractor.java:114)
        at edu.harvard.hul.ois.fits.tools.ToolBase.run(ToolBase.java:271)
        at java.base/java.lang.Thread.run(Unknown Source)
2023-02-28 18:51:58 - ERROR - MetadataExtractor:122 - NLNZ Metadata Extractor error while harvesting file: java.lang.RuntimeException
2023-02-28 18:51:59 - ERROR - Fits:683 - Tool error processing file: 20775-bb0000854v-1-1.mp3
NLNZ Metadata Extractor error while harvesting file 20775-bb0000854v-1-1.mp3 (java.io.FileNotFoundException: dams4/bb/00/00/85/4v/20775-bb0000854v-1-1.mp3 (Permission denied))
edu.harvard.hul.ois.fits.exceptions.FitsToolException: NLNZ Metadata Extractor error while harvesting file 20775-bb0000854v-1-1.mp3 (java.io.FileNotFoundException: dams4/bb/00/00/85/4v/20775-bb0000854v-1-1.mp3 (Permission denied))
        at edu.harvard.hul.ois.fits.tools.nlnz.MetadataExtractor.extractInfo(MetadataExtractor.java:124) ~[fits-1.6.0-SNAPSHOT.jar:1.6.0-SNAPSHOT]
        at edu.harvard.hul.ois.fits.tools.ToolBase.run(ToolBase.java:271) ~[fits-1.6.0-SNAPSHOT.jar:1.6.0-SNAPSHOT]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd" version="1.6.0-SNAPSHOT" timestamp="2/28/23, 6:51 PM">
  <identification>
    <identity format="MPEG 1/2 Audio Layer 3" mimetype="audio/mpeg" toolname="FITS" toolversion="1.6.0-SNAPSHOT">
      <tool toolname="Droid" toolversion="6.5.2" />
      <tool toolname="Exiftool" toolversion="12.50" />
      <tool toolname="ffident" toolversion="0.2" />
      <tool toolname="Tika" toolversion="2.6.0" />
      <externalIdentifier toolname="Droid" toolversion="6.5.2" type="puid">fmt/134</externalIdentifier>
    </identity>
  </identification>
  <fileinfo>
    <filepath toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">/work/dams4/bb/00/00/85/4v/20775-bb0000854v-1-1.mp3</filepath>
    <filename toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">20775-bb0000854v-1-1.mp3</filename>
    <size toolname="OIS File Information" toolversion="1.0">2353152</size>
    <md5checksum toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">75b19403b63f1646181a20e5907265ea</md5checksum>
    <fslastmodified toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">1368217801000</fslastmodified>
  </fileinfo>
  <filestatus />
  <metadata>
    <audio>
      <bitRate toolname="Exiftool" toolversion="12.50" status="SINGLE_RESULT">160 kbps</bitRate>
      <sampleRate toolname="Exiftool" toolversion="12.50">44100</sampleRate>
      <channels toolname="Exiftool" toolversion="12.50">2</channels>
      <author toolname="Tika" toolversion="2.6.0" status="SINGLE_RESULT">Monteverdi Choir et al (director, John Eliot Gardiner)</author>
      <title toolname="Tika" toolversion="2.6.0" status="SINGLE_RESULT">St. Matthew Passion: O Schmerz! Hier zittert das gequalte Herz/Was ist die Ursach' aller solcher Plagen</title>
      <sampleRate toolname="Tika" toolversion="2.6.0" status="SINGLE_RESULT">44100</sampleRate>
    </audio>
  </metadata>
  <statistics fitsExecutionTime="560">
    <tool toolname="MediaInfo" toolversion="22.09" status="did not run" />
    <tool toolname="OIS Audio Information" toolversion="0.1" status="did not run" />
    <tool toolname="ADL Tool" toolversion="0.1" status="did not run" />
    <tool toolname="VTT Tool" toolversion="0.1" status="did not run" />
    <tool toolname="Droid" toolversion="6.5.2" executionTime="305" />
    <tool toolname="Jhove" toolversion="1.26.1" status="did not run" />
    <tool toolname="embARC" toolversion="0.2" status="did not run" />
    <tool toolname="file utility" toolversion="5.43" executionTime="538" />
    <tool toolname="Exiftool" toolversion="12.50" executionTime="524" />
    <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" status="failed" />
    <tool toolname="OIS File Information" toolversion="1.0" executionTime="120" />
    <tool toolname="OIS XML Metadata" toolversion="0.2" status="did not run" />
    <tool toolname="ffident" toolversion="0.2" executionTime="471" />
    <tool toolname="Tika" toolversion="2.6.0" executionTime="243" />
    <tool toolname="jpylyzer" toolversion="2.1.0" status="did not run" />
  </statistics>
</fits>

**Comment by pwinckles** [comment]
Unfortunately, that's a bug in NLNZ Metadata Extractor and not FITS. As far as I can tell, that tool is essentially abandoned, but you could try cutting them a ticket https://github.com/DIA-NZ/Metadata-Extraction-Tool
