### ISSUE TITLE
MediaInfo for FITS version 1.5.5 does not work

### ISSUE THREAD

**Issue by patelanm** [harvard-lts/fits#385]
I am trying to run the FITS version 1.5.5. The MediaInfo configuration works completely fine for version 1.5.0, but when I upgraded the FITS version to 1.5.5 and tried to run the code I am seeing below error message.

`<tool toolname="MediaInfo" toolversion="[could not launch tool]" status="failed"/>`

It should show "did not run" instead of "failed" status.

I also compared all the files in both the versions 1.5.0 an 1.5.5 and everything looks identical.

Can someone please help me with this?

**Comment by pwinckles** [comment]
@patelanm

1. Can you look for errors in the fits log file and post what you find?
2. Is there a reason you upgraded to 1.5.5 instead of 1.6.0?

**Comment by patelanm** [comment]
@pwinckles I initially upgraded to 1.6.0 but wasn't able to disable TIKA so we decided to upgrade to 1.5.5 
Also I am not able to find any log files. The business owner is requesting to disable it and show the status "did not run". Is there a way to do that?

**Comment by pwinckles** [comment]
@patelanm Yes, but you haven't provided enough information in either of your tickets for us to help you. Please provide your config in https://github.com/harvard-lts/fits/issues/384.

**Comment by patelanm** [comment]
Here is my fits config file content:

<?xml version="1.0" encoding="UTF-8"?>
<fits_configuration>
	
	<tools>
		
        
        
        <tool class="edu.harvard.hul.ois.fits.tools.mediainfo.MediaInfo" include-exts="avi,mov,mpg,mpeg,mkv,mp4,mxf,ogv,mj2,divx,dv,m4v,m2v,ismv,m2ts,mpeg4,rmvb,wmv,3gp,3g2,rm" classpath-dirs="lib/mediainfo" />
        <tool class="edu.harvard.hul.ois.fits.tools.oisfileinfo.AudioInfo" include-exts="wav" classpath-dirs="lib/audioinfo" />
        <tool class="edu.harvard.hul.ois.fits.tools.oisfileinfo.ADLTool" include-exts="adl" classpath-dirs="lib/adltool" />
        <tool class="edu.harvard.hul.ois.fits.tools.oisfileinfo.VTTTool" include-exts="vtt" />
        <tool class="edu.harvard.hul.ois.fits.tools.droid.Droid"  exclude-exts="odm,m4a,mpg" classpath-dirs="lib/droid" />
        <tool class="edu.harvard.hul.ois.fits.tools.jhove.Jhove" exclude-exts="dng,mbx,mbox,arw,adl,eml,java,doc,docx,docm,odt,rtf,pages,wpd,wp,epub,csv,avi,mov,mpg,mpeg,mkv,mp3,mp4,mpeg4,m2ts,mxf,ogv,mj2,divx,dv,m4v,m2v,ismv,pcd,zip" classpath-dirs="lib/jhove" />
        <tool class="edu.harvard.hul.ois.fits.tools.fileutility.FileUtility" exclude-exts="dng,wps,adl,jar,epub,csv,m4a" classpath-dirs="lib/fileutility" />
        <tool class="edu.harvard.hul.ois.fits.tools.exiftool.Exiftool" exclude-exts="txt,wps,vsd,jar,avi,mov,mpg,mpeg,mkv,mp4,mxf,ogv,mj2,divx,dv,m4v,m2v,ismv,m2ts,mpeg4,rmvb,rm,wmv" classpath-dirs="lib/exiftool" />
        <tool class="edu.harvard.hul.ois.fits.tools.nlnz.MetadataExtractor" include-exts="bmp,gif,jpg,jpeg,wp,wpd,odt,doc,pdf,mp3,bfw,flac,html,xml,arc,tif,tiff" classpath-dirs="lib/nzmetool,xml/nlnz"/>
        <tool class="edu.harvard.hul.ois.fits.tools.oisfileinfo.FileInfo" classpath-dirs="lib/fileinfo" />
        <tool class="edu.harvard.hul.ois.fits.tools.oisfileinfo.XmlMetadata" include-exts="xml" classpath-dirs="lib/xmlmetadata" />
        <tool class="edu.harvard.hul.ois.fits.tools.ffident.FFIdent" exclude-exts="dng,wps,vsd,jar,ppt,rtf" classpath-dirs="lib/ffident" />
        <tool class="edu.harvard.hul.ois.fits.tools.tika.TikaTool" exclude-exts="jar,avi,mov,mpg,mpeg,mkv,mp4,mpeg4,m2ts,mxf,ogv,mj2,divx,dv,m4v,m2v,ismv,tif,tiff" classpath-dirs="lib/tika"/>
	</tools>

	<output>
		<dataConsolidator class="edu.harvard.hul.ois.fits.consolidation.OISConsolidator"/>
		<display-tool-output>true</display-tool-output>
		<report-conflicts>true</report-conflicts>
		<validate-tool-output>false</validate-tool-output>
		<internal-output-schema>xml/fits_output.xsd</internal-output-schema>
		<external-output-schema>http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd</external-output-schema>
		<fits-xml-namespace>http://hul.harvard.edu/ois/xml/ns/fits/fits_output</fits-xml-namespace>
		<enable-statistics>true</enable-statistics>
		<enable-checksum>true</enable-checksum>
		
		
		
		
		
	</output>

	<process>
		<max-threads>20</max-threads>
	</process>

	
	<droid_sigfile>DROID_SignatureFile_V94_Alt.xml</droid_sigfile>
	
	
	

</fits_configuration>

**Comment by pwinckles** [comment]
@patelanm I would rather help you get 1.6.0 working than 1.5.5. Here's the relevant file in regards to Tika in your configuration:

```xml
<tool class="edu.harvard.hul.ois.fits.tools.tika.TikaTool" exclude-exts="jar,avi,mov,mpg,mpeg,mkv,mp4,mpeg4,m2ts,mxf,ogv,mj2,divx,dv,m4v,m2v,ismv,tif,tiff" classpath-dirs="lib/tika"/>
```

Now, which file extension were you attempting to exclude from Tika?

**Comment by patelanm** [comment]
Below is the response I got from my product owner:

Our FITS is only pointing to the IMAGES folder to look for image files, i.e., there will be no txt, doc or video files shown in the folder at all. Do we still have to list all those file extensions for exclusion? Currently, we only have .tif or .tiff but we had .jpeg in the past. We may have .jp2 in the future.

If we have to list all of them regardless, then we will want them to provides us a complete file extension list Tika is programmed to look for.

**Comment by dchandekstark** [comment]
I can confirm this problem as well, at least on Debian bookworm.  Installing the mediainfo OS package and removing tools/mediainfo from FITS makes no difference.

**Comment by pwinckles** [comment]
@dchandekstark are you using version 1.5.5? If so, why?

**Comment by dchandekstark** [comment]
@pwinckles Yes, using 1.5.5.  I had some issue with 1.6.0 but TBH can't remember now ... will give it a try.

**Comment by pwinckles** [comment]
@dchandekstark the latest version of MediaInfo does not work with pre-1.6.0 releases. I strongly recommend using 1.6.0. If you have issues with it, open a new ticket.
