### ISSUE TITLE
Sax Errorhandler error (FITS 0.6.3)

### ISSUE THREAD

**Issue by techmaurice** [harvard-lts/fits#4]
This error keeps randomly occuring:
<code>
Warning: validation was turned on but an org.xml.sax.ErrorHandler was not
set, which is probably not what is desired.  Parser will use a default
ErrorHandler to print the first 10 errors.  Please call
the 'setErrorHandler' method to fix this.
Error: URI=null Line=2: cvc-elt.1: Cannot find the declaration of element 'fits'
.
</code>

**Comment by atz** [comment]
@techmaurice is this issue fixed in a more recent release?

**Comment by daveneiman** [comment]
As this issue is well before my time, I can't say whether it's been fixed. Would need to know where in the code this was an issue as there's no indication in the original post.
