### ISSUE TITLE
Upgrade DROID install to 6.1.5 so as to support Java8

### ISSUE THREAD

**Issue by ross-spencer** [harvard-lts/fits#40]
Fits currently won't run DROID when working under Java 8. 

It does however fail gracefully. 

N.B. 6.1.5 also brings with it better UTF-8 support, which I currently can't test in FITS while being on Java 8.

**Comment by daveneiman** [comment]
The next release of FITS will contain the the DROID upgrade to v.6.1.5 and will work with Java 8.

**Comment by ross-spencer** [comment]
Great news. Thanks!

**Comment by daveneiman** [comment]
Update: The next release of FITS will contain the addition of the MediaInfo tool. The DROID update mentioned here will follow that release soon thereafter.

**Comment by tulikagupta** [comment]
I am waiting for Support with Java 8. Is there any expected date, when this will be implemented?

**Comment by daveneiman** [comment]
We are in the process of testing the MediaInfo release and hope to release it within the next 2 weeks. That will be followed by the DROID update a few weeks later. Sorry for the delay.

**Comment by tulikagupta** [comment]
Thanks for update.

**Comment by tulikagupta** [comment]
Hi,

Is there any plan to start supporting Java 8 compatible Release before end of this year?

**Comment by daveneiman** [comment]
Yes, this is. We have needed to upgrade the JHOVE tool contained within FITS. This has set us back a bit more. We're aiming to have the next release out within a couple of weeks.

**Comment by jcoyne** [comment]
What's the status on this?  Still a couple of weeks out? :wink:

**Comment by daveneiman** [comment]
DROID 6.1.5 was included in the 0.9.0 release some time ago. There is an even more current release available here and on http://fitstool.org.

**Comment by jcoyne** [comment]
@daveneiman that's great. Is there some reason this ticket should remain open?

**Comment by daveneiman** [comment]
Nope. Oversight on my part. Thanks for the reminder.
