### ISSUE TITLE
libmediainfo.so.0 is not built for CentOS Linux, causes "Error loading native library for MediaInfo please check that fits_home is properly set"

### ISSUE THREAD

**Issue by cameronkerrnz** [harvard-lts/fits#41]
Using current master

```
$ find tools/mediainfo/
tools/mediainfo/
tools/mediainfo/linux
tools/mediainfo/linux/centos                                <--- No mediainfo for CentOS
tools/mediainfo/linux/centos/libzen.so
tools/mediainfo/linux/libzen.so
tools/mediainfo/linux/ubuntu
tools/mediainfo/linux/ubuntu/libmediainfo.so.0   <--- Included for Ubuntu
tools/mediainfo/linux/ubuntu/libzen.so.0
tools/mediainfo/linux/libzen.so.0
tools/mediainfo/mac
tools/mediainfo/mac/Changes.txt
tools/mediainfo/mac/History.txt
tools/mediainfo/mac/ReadMe.txt
tools/mediainfo/mac/libmediainfo.0.dylib
tools/mediainfo/mac/libmediainfo.dylib
tools/mediainfo/windows
tools/mediainfo/windows/64
tools/mediainfo/windows/64/Changes.txt
tools/mediainfo/windows/64/MediaInfo.dll
tools/mediainfo/windows/64/ReadMe.txt
```

Running as per the README.md

```
$ ./fits.sh -i RELEASE.txt
...
2015-08-31 23:44:21,575 ERROR [main] ToolBelt:79 - Thread 1 error initializing edu.harvard.hul.ois.fits.tools.mediainfo.MediaInfo: edu.harvard.hul.ois.fits.exceptions.FitsToolException  Message: Error loading native library for MediaInfo please check that fits_home is properly set
...
```

strace tells me it was looking for libmediainfo.so and didn't find it.

I see that libmediainfo and libzen are both available from EPEL (for RHEL7), so presumably mediainfo is meant to come from there?

```
# yum install libmediainfo libzen
```

This will install (currently RHEL 7.1) libmediainfo-0.7.74-1.el7.x86_64.rpm, libzen-0.4.31-2.el7.x86_64.rpm and include a dependency on tinyxml2-2.1.0-2.20140406git6ee53e7.el7.x86_64.rpm

You may like to update your documentaion, it took ah hour for me to figure out what was happening, and didn't see anything about such a dependency in the documentation.

Cheers,
Cameron

**Comment by DaveSiegel** [comment]
Dave B. is out of the office but will answer you're questions as soon as he's back tomorrow.

**Comment by dbirtwellharvard** [comment]
Cameron:

I apologize for any inconvenience we caused.

Some files that were supposed to have been pushed/merged to the master branch, namely the MediaInfo libraries,  seem to have not made it to GitHub. I pushed them today to GitHub, so they should be there now.

We recommend that you use the versions of the MediaInfo libraries that are distributed with the FITS releases to maintain compatibility with that particular version of FITS, or use those in GitHub, if you are building your own release. In this case, there isn't yet a FITS release and the files were somehow missed during the merge ... so you didn't have a choice.

The documentation for FITS has not been yet been updated to detail the support Video files and MediaInfo, as we have not yet released the updated release of FITS.

We plan to do an official release of FITS soon, which will including updated documentation. It is very possible that some of the other tools will be updated to the latest version (or at least more recent versions). We are deciding what to include, other than MediaInfo support, and this is one of the reasons that an official FITS release had not been made to match the code in the MASTER.

BTW - only 64-bit versions of OSes will be officially supported for Video file support using MediaInfo as the tool for harvesting metadata details. As you can tell from the directory structure, at this time, we will only be officially supporting Windows 64-bit, Mac OS 64-bit (I believe OS X and above), CentOS 64-bit and Ubuntu 64-bit. CentOS is the 64-bit LINUX used out-of-the-box. If you wish to use Ubuntu, you have to copy the libmediainfo.so.0 and libzen.so.0 files from tools/mediainfo/linux/ubuntu to tools/mediainfo/linux (overwriting the ones there, which are for CentOS).

I hope this explains what happened.

Thanks,

Dave Birtwell

**Comment by cameronkerrnz** [comment]
Excellent. Thank you very much.

**Comment by randystern** [comment]
Hi Cameron,

Just for our edification, what project and/or institution are you associated with that is using FITS?

Randy Stern
Director of Systems Development
Harvard University IT, Library Technology Services

**Comment by cameronkerrnz** [comment]
I'm working on deploying a Digital Asset Management project for the University of Otago Library in New Zealand. 

Cheers, Cameron

**Comment by randystern** [comment]
Thanks!  1 day, 2 hours away from Cambridge, per Google maps!

**Comment by little9** [comment]
Hi, 

Thank you for developing FITS!  

I'm running FITS 1.0.2 on Ubuntu 16.04 (64-bit) and am getting the the same ""Error loading native library for MediaInfo" error. It looks like the tools/mediainfo/linux/ folder no longer has ubuntu and centos folders. If I am using ubuntu do I need to grab those files from an older release? 

Thanks,
Jamie

**Comment by little9** [comment]
I see the info for this in the FAQ (http://projects.iq.harvard.edu/fits/fitsfaq) 

Thanks!

**Comment by Toputnal** [comment]
We're running FITS 1.0.5 on RHEL 7 (which only exists as 64-bit).  We needed to export the following variable in order to resolve this issue, for our case, at least.  
     LD_LIBRARY_PATH=/usr/local/bin/fits-1.0.5/tools/mediainfo/linux
