### ISSUE TITLE
Maven Repository

### ISSUE THREAD

**Issue by maksimu** [harvard-lts/fits#42]
Do you have any plans to place this library to Maven?

**Comment by dbirtwellharvard** [comment]
Sorry, there are no current plans to move FITS to a maven build environment.

Also, just an FYI,there is a FITS users Google Group commonly used for FITS questions.

It's at:

https://groups.google.com/forum/#!forum/fits-users

Thanks,

Dave B.

**Comment by fungunga** [comment]
Hi there! I tried some weeks ago to port this to maven, please have a look there: https://github.com/fungunga/fits
All dependencies are solved, every library found, but tests are not running, surely I am not IN THE CODE enough… please feel free to try…

**Comment by daveneiman** [comment]
Great going! Will be able to take a look at some point in the future. Curious where you put ots-<x.x>.jar which is a dependency internal to our group. Yes, fits.jar would be the main build artifact of the project. However, I had envisioned using something like the assembly plugin to create the fits.zip artifact which is deployed to the http://fitstool.org site.

**Comment by daveneiman** [comment]
Have pulled your code and experimented with converting the current version of FITS to Maven. So far have project compiling and all tests working. Still, do not yet have ZIP file being built and many dependencies are not in a Maven repository so must be stored locally. Also, will need to update many dependencies to newer versions -- some are many, many years old and outdated. Thanks for sharing your project so I could have a good starting point.

**Comment by fungunga** [comment]
Yes! That's soo nice! :-) Glad I could help!

**Comment by fungunga** [comment]
And: It is Issue #42!
