### ISSUE TITLE
ClassLoader problems creating instance of transformerfactory

### ISSUE THREAD

**Issue by nclarkekb** [harvard-lts/fits#48]
ToolBase.java has a classloader problem loading saxon using transformerfactory.
This can be fixed by passing the classloader used to load the class itself as the second parameter instead of null.

```
    tFactory = TransformerFactory.newInstance("net.sf.saxon.TransformerFactoryImpl",null);
```

should be

```
    tFactory = TransformerFactory.newInstance("net.sf.saxon.TransformerFactoryImpl",this.getClass().getClassLoader());
```

**Comment by daveneiman** [comment]
No problem was evident and no details of the problem described in this issue. If the problem persists, please open a new issue with specific details. Thanks.

**Comment by nclarkekb** [comment]
If you want to use a custom classloader then passing null to all xml factories will creates major classloader problems. On the other hand the custom classloader added in later fits versions looked fairly alternative so that will probably also cause problems.
Just to be clear I wrapped fits 0.8.x in a custom classloader so it would be completely isolated while being run inside a tomcat webapp. (To isolate its jars from droid, tika, etc.)
If I actually need to run this in production I will fix those classloader issues and submit a pull request instead.

**Comment by daveneiman** [comment]
The `null` was replaced by the ToolBase classloader in a commit on Nov. 23, 2015:
`tFactory = TransformerFactory.newInstance("net.sf.saxon.TransformerFactoryImpl", ToolBase.class.getClassLoader());`
