### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by pdurbin** [harvard-lts/fits#51]
I just saw "We have a goal of developing an open source community process right now for FITS" at https://wiki.harvard.edu/confluence/display/LibraryStaffDoc/Harvard+Library+Open+Source+Project+Considerations and would like to suggest that you add a CONTRIBUTING.md file to the root of the git repo per https://help.github.com/articles/setting-guidelines-for-repository-contributors/

That GitHub article has links to some examples:
- https://github.com/atom/atom/blob/master/CONTRIBUTING.md
- https://github.com/rails/rails/blob/master/CONTRIBUTING.md
- https://github.com/opengovernment/opengovernment/blob/master/CONTRIBUTING.md

I work on Dataverse and here's ours: https://github.com/IQSS/dataverse/blob/master/CONTRIBUTING.md

Not only does it help potential contributors know how to help, it also puts "Please review the guidelines for contributing to this repository" (with a link to CONTRIBUTING.md) at the top of the page when users go to open a new issue.

**Comment by randystern** [comment]
Great idea, thanks Phil.

**Comment by atz** [comment]
This appears to be done, and closeable:
https://github.com/harvard-lts/fits/blob/dev/CONTRIBUTING.md

Also, greetings to @pdurbin from across the Internet and decades.

**Comment by pdurbin** [comment]
To you too, @atz ! 😄

**Comment by daveneiman** [comment]
Thanks for your input. For the time being, we currently have no official dedicated support for FITS so your input is much appreciated.
