### ISSUE TITLE
tooloutput is not generated with new FITS

### ISSUE THREAD

**Issue by tulikagupta** [harvard-lts/fits#53]
Hi,

I am trying to run FITS 0.9.0 for tiff file, generated XML doesn't have toolOutput tag. 

Thanks,
Tulika

**Comment by daveneiman** [comment]
Hi Tulika,

This is (and has been) turned off by default. If you open your xml/fits.xml file find the following element:
<display-tool-output>false</display-tool-output>
Change this value to true and then you should see the output.

Cheers,
David N.

**Comment by tulikagupta** [comment]
It worked. Thank you
