### ISSUE TITLE
fits.bat not handling white space in directory path on Windows 7

### ISSUE THREAD

**Issue by jmcdonou** [harvard-lts/fits#69]
I'm using FITS in a digital preservation class, and multiple students reported that the program was not working under Windows 7 or 8 with Java 1.8 installed, report a class not found error:

Error: Could not find or load main class Files\fits-0.10.0\xml\nlnz;lib\AES31.jar; etc., etc., etc.

Testing on a Windows 7 machine, I reproduced their error when FITS is installed under C:\Program Files\ as in the installation instructions.  However, it does not occur when installed in a directory which has no space character in the directory bat.  It looks to me like fits.bat needs to be altered to make sure it's properly escaping space characters when using the APPCLASSPATH variable in the final 'java -classpath' command.

**Comment by daveneiman** [comment]
Thanks for the heads-up on this. We will be looking into this in the near future.

**Comment by daveneiman** [comment]
This issue has been resolved but will not be released until the next major FITS release. In the mean time the fix can be accomplished by opening the fits.bat file and either removing or commenting out this line:
set JARS="%FITS_HOME%\xml\nlnz"
This line is no longer necessary and should have been removed in a previous release.
